# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shireguard < Formula
  desc "WireGuard P2P connectivity"
  homepage "https://shireguard.com"
  version "0.1.30"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doppiscantsleep/shireguard/releases/download/v0.1.30/shireguard_darwin_amd64.tar.gz"
      sha256 "2adf6921fb00673269a5ab9b84ceeb6c598d1be2dc16bf7c8bdc28e406357b68"

      define_method(:install) do
        bin.install "shireguard"
        bin.install "shireguard-menubar"
        # Wrap shireguard-menubar into an .app bundle in the prefix
        app_bundle = prefix/"ShireguardMenuBar.app/Contents/MacOS"
        app_bundle.mkpath
        (prefix/"ShireguardMenuBar.app/Contents").install_symlink bin/"shireguard-menubar" => "MacOS/shireguard-menubar"
        (prefix/"ShireguardMenuBar.app/Contents/Info.plist").write <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key><string>ShireguardMenuBar</string>
              <key>CFBundleDisplayName</key><string>Shireguard</string>
              <key>CFBundleIdentifier</key><string>com.shireguard.menubar</string>
              <key>CFBundleVersion</key><string>1</string>
              <key>CFBundleExecutable</key><string>shireguard-menubar</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>LSUIElement</key><true/>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
        PLIST
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doppiscantsleep/shireguard/releases/download/v0.1.30/shireguard_darwin_arm64.tar.gz"
      sha256 "2b1fa2d7365e15833c16264607ddbe373b3e2024982b1ac5f35fc4f5d1a1db17"

      define_method(:install) do
        bin.install "shireguard"
        bin.install "shireguard-menubar"
        # Wrap shireguard-menubar into an .app bundle in the prefix
        app_bundle = prefix/"ShireguardMenuBar.app/Contents/MacOS"
        app_bundle.mkpath
        (prefix/"ShireguardMenuBar.app/Contents").install_symlink bin/"shireguard-menubar" => "MacOS/shireguard-menubar"
        (prefix/"ShireguardMenuBar.app/Contents/Info.plist").write <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key><string>ShireguardMenuBar</string>
              <key>CFBundleDisplayName</key><string>Shireguard</string>
              <key>CFBundleIdentifier</key><string>com.shireguard.menubar</string>
              <key>CFBundleVersion</key><string>1</string>
              <key>CFBundleExecutable</key><string>shireguard-menubar</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>LSUIElement</key><true/>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
        PLIST
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doppiscantsleep/shireguard/releases/download/v0.1.30/shireguard_linux_amd64.tar.gz"
      sha256 "15215b9e307e3712f348a75844af70a30996861509c20842178e51e5e1112f07"
      define_method(:install) do
        bin.install "shireguard"
        bin.install "shireguard-menubar"
        # Wrap shireguard-menubar into an .app bundle in the prefix
        app_bundle = prefix/"ShireguardMenuBar.app/Contents/MacOS"
        app_bundle.mkpath
        (prefix/"ShireguardMenuBar.app/Contents").install_symlink bin/"shireguard-menubar" => "MacOS/shireguard-menubar"
        (prefix/"ShireguardMenuBar.app/Contents/Info.plist").write <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key><string>ShireguardMenuBar</string>
              <key>CFBundleDisplayName</key><string>Shireguard</string>
              <key>CFBundleIdentifier</key><string>com.shireguard.menubar</string>
              <key>CFBundleVersion</key><string>1</string>
              <key>CFBundleExecutable</key><string>shireguard-menubar</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>LSUIElement</key><true/>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
        PLIST
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doppiscantsleep/shireguard/releases/download/v0.1.30/shireguard_linux_arm64.tar.gz"
      sha256 "6d355fe8d7f170dba09aa890c64325deaf5dea2389dddf55219ace07fa5e71e7"
      define_method(:install) do
        bin.install "shireguard"
        bin.install "shireguard-menubar"
        # Wrap shireguard-menubar into an .app bundle in the prefix
        app_bundle = prefix/"ShireguardMenuBar.app/Contents/MacOS"
        app_bundle.mkpath
        (prefix/"ShireguardMenuBar.app/Contents").install_symlink bin/"shireguard-menubar" => "MacOS/shireguard-menubar"
        (prefix/"ShireguardMenuBar.app/Contents/Info.plist").write <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key><string>ShireguardMenuBar</string>
              <key>CFBundleDisplayName</key><string>Shireguard</string>
              <key>CFBundleIdentifier</key><string>com.shireguard.menubar</string>
              <key>CFBundleVersion</key><string>1</string>
              <key>CFBundleExecutable</key><string>shireguard-menubar</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>LSUIElement</key><true/>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
        PLIST
      end
    end
  end

  test do
    system "#{bin}/shireguard", "--version"
  end
end
