# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shireguard < Formula
  desc "WireGuard P2P connectivity"
  homepage "https://shireguard.com"
  version "0.1.26"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doppiscantsleep/shireguard/releases/download/v0.1.26/shireguard_darwin_amd64.tar.gz"
      sha256 "d57e831e4659f7ca36d792d70ba841ab40480b00b70802f82f34047cb5a25223"

      define_method(:install) do
        bin.install "shireguard"
        bin.install "shireguard-menubar"
        # Wrap shireguard-menubar into an .app bundle in the prefix
        app_bundle = prefix/"ShireguardMenuBar.app/Contents/MacOS"
        app_bundle.mkpath
        (prefix/"ShireguardMenuBar.app/Contents").install_symlink bin/"shireguard-menubar" => "MacOS/shireguard-menubar"
        (prefix/"ShireguardMenuBar.app/Contents/Info.plist").write <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key><string>ShireguardMenuBar</string>
              <key>CFBundleDisplayName</key><string>Shireguard</string>
              <key>CFBundleIdentifier</key><string>com.shireguard.menubar</string>
              <key>CFBundleVersion</key><string>1</string>
              <key>CFBundleExecutable</key><string>shireguard-menubar</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>LSUIElement</key><true/>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
        PLIST
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doppiscantsleep/shireguard/releases/download/v0.1.26/shireguard_darwin_arm64.tar.gz"
      sha256 "355012a38a2ad2bafbf6e48536fe320d01dedba13bd8fd21d7725599d9ef9780"

      define_method(:install) do
        bin.install "shireguard"
        bin.install "shireguard-menubar"
        # Wrap shireguard-menubar into an .app bundle in the prefix
        app_bundle = prefix/"ShireguardMenuBar.app/Contents/MacOS"
        app_bundle.mkpath
        (prefix/"ShireguardMenuBar.app/Contents").install_symlink bin/"shireguard-menubar" => "MacOS/shireguard-menubar"
        (prefix/"ShireguardMenuBar.app/Contents/Info.plist").write <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key><string>ShireguardMenuBar</string>
              <key>CFBundleDisplayName</key><string>Shireguard</string>
              <key>CFBundleIdentifier</key><string>com.shireguard.menubar</string>
              <key>CFBundleVersion</key><string>1</string>
              <key>CFBundleExecutable</key><string>shireguard-menubar</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>LSUIElement</key><true/>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
        PLIST
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doppiscantsleep/shireguard/releases/download/v0.1.26/shireguard_linux_amd64.tar.gz"
      sha256 "0a56f4fbfeed05d67612df2bdd94dc85c0aff6b827fd5d274e5fbc282104c3a6"
      define_method(:install) do
        bin.install "shireguard"
        bin.install "shireguard-menubar"
        # Wrap shireguard-menubar into an .app bundle in the prefix
        app_bundle = prefix/"ShireguardMenuBar.app/Contents/MacOS"
        app_bundle.mkpath
        (prefix/"ShireguardMenuBar.app/Contents").install_symlink bin/"shireguard-menubar" => "MacOS/shireguard-menubar"
        (prefix/"ShireguardMenuBar.app/Contents/Info.plist").write <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key><string>ShireguardMenuBar</string>
              <key>CFBundleDisplayName</key><string>Shireguard</string>
              <key>CFBundleIdentifier</key><string>com.shireguard.menubar</string>
              <key>CFBundleVersion</key><string>1</string>
              <key>CFBundleExecutable</key><string>shireguard-menubar</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>LSUIElement</key><true/>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
        PLIST
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doppiscantsleep/shireguard/releases/download/v0.1.26/shireguard_linux_arm64.tar.gz"
      sha256 "10a6c77ffdf2699c16e4eee19b5bfae601faff7ca4bcf829a54299403b2033d0"
      define_method(:install) do
        bin.install "shireguard"
        bin.install "shireguard-menubar"
        # Wrap shireguard-menubar into an .app bundle in the prefix
        app_bundle = prefix/"ShireguardMenuBar.app/Contents/MacOS"
        app_bundle.mkpath
        (prefix/"ShireguardMenuBar.app/Contents").install_symlink bin/"shireguard-menubar" => "MacOS/shireguard-menubar"
        (prefix/"ShireguardMenuBar.app/Contents/Info.plist").write <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key><string>ShireguardMenuBar</string>
              <key>CFBundleDisplayName</key><string>Shireguard</string>
              <key>CFBundleIdentifier</key><string>com.shireguard.menubar</string>
              <key>CFBundleVersion</key><string>1</string>
              <key>CFBundleExecutable</key><string>shireguard-menubar</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>LSUIElement</key><true/>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
        PLIST
      end
    end
  end

  test do
    system "#{bin}/shireguard", "--version"
  end
end
